version: "3.9"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports: 
      - 8086:8086
    volumes:
      - /home/docker/influxdb:/root/influxdb2
    networks:
      - grafana_grafana
      - metrics
    environment:
      DOCKER_INFLUXDB_INIT_USERNAME: krjnk
      DOCKER_INFLUXDB_INIT_PASSWORD: jelen666
      DOCKER_INFLUXDB_INIT_ORG: KRNJCORP
      DOCKER_INFLUXDB_INIT_BUCKET: test
networks:
  grafana_grafana:
    external: true
    name: grafana_grafana
  metrics:
    driver: bridge
